### ISSUE TITLE
Figure out how to port-forward to cromwell server from within docker image

### ISSUE THREAD

**Issue by alexwaldrop** [RTIInternational/wdl_input_tools#2]

**Comment by bryancquach** [comment]
# Issue details

As part of executing the Python scripts from the [`wdl_input_tools`](https://github.com/RTIInternational/wdl_input_tools/tree/master) repo from within a Docker container, the container network configuration must be setup so that the container can access the host machine's localhost. This is because an SSH tunnel is established between the host machine and the Cromwell server via localhost through port 8000.

---

# Solution

## Overview

It was identified that on some systems Docker does not listen to the host machine localhost address by default. This can be resolved one of two ways:
1. Use `docker run --network=host` to enable Docker to use the host machine network configuration. This would mean that the Docker container could access the Cromwell server through `localhost:8000` if the host machine exposes `localhost:8000` for SSH tunneling to the Cromwell server.
1. Change the host machine SSH tunneling to expose the default Docker network address instead of `localhost`.

----
# Solution 1: Enable Docker to use the host machine network configuration

With this approach you would SSH tunnel from the host machine to the Cromwell server as follows:
```bash
ssh -fN -i <private key file> -L localhost:8000:localhost:8000 ec2-user@<Cromwell server IP>
```

When using `wdl_input_tools` scripts that contact the Cromwell server within a Docker container, include `docker run --network=host` and set `--cromwell-url localhost:8000`. For example:

```bash
docker run \
  --rm \
  --network=host \
  -v /mnt/c/Users/bquach/projects/hiv/wihs_alternative_splicing/analysis/1_munging/0001/0001:/scratch \
  -t bryancquach/rnaseq_wdl:202310070954_x86_64 \
  make_batch_inputs.py \
    --batch-config /scratch/configs/rnaseq_pe_wf_20231017.yaml \
    --sample-sheet /scratch/tables/sample_sheet_rnaseq_pe_wf_20231017.xlsx \
    --batch-name rnaseq_pe_wf_20231017 \
    --cromwell-url localhost:8000 \
    --output-dir /scratch/configs/ \
    -vv
```

----
# Solution 2: Enable SSH tunneling to use the Docker network address

With this approach we need to first get the Docker network address using the command :
```bash
ip addr show docker0 | grep -Po 'inet \K[\d.]+'
```
Let's assume this returns the IP `222.19.0.1`. Then `/etc/hosts` needs to be updated to include the following additional line:

```
222.19.0.1 host.docker.internal
```

SSH tunneling would then be implemented as follows:

```bash
ssh -fN -i <private key file> -L 222.19.0.1:8000:localhost:8000 ec2-user@<Cromwell server IP>
```

When using `wdl_input_tools` scripts that contact the Cromwell server within a Docker container, include `docker run --add-host=host.docker.internal:host-gateway` and set `--cromwell-url host.docker.internal:8000`.
